import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider
} from '@clerk/nextjs';
import { envConfig } from "@/constants/envConfig";
import { Toaster } from "@/components/ui/toaster";

const geistSans = IBM_Plex_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  fallback: ["system-ui", "sans-serif"],
  preload: true,
  adjustFontFallback: true,
});

const geistMono = IBM_Plex_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  fallback: ["system-ui", "monospace"],
  preload: true,
  adjustFontFallback: true,
});

export const metadata: Metadata = {
  title: "Budh Bhraman",
  description: "Generated by create next app",
  category: "Travel",
  keywords: [
    "budh bhraman",
    "travel blog",
    "north east india",
    "india travel",
    "sikim",
    "assam",
    "travel",
    "tourism",
    "adventure",
    "exploration",
    "culture",
    "nature",
    "vacation",
    "wanderlust",
    "sightseeing",
    "holiday",
    "destinations",
    "travel tips",
    "itinerary",
    "travel guide",
    "travel photography",
    "travel blog",
    "travel stories",
    "travel experiences",
    "travel inspiration",
    "travel planning",
    "travel community"
  ],
  authors: [
    {
      name: "DRLOVE",
      url: "https://drlov.netlify.app"
    }
  ],
  publisher:"Budh bhraman"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    publishableKey={envConfig.clerkPublishableKey}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
